[profile.default]
src = "src"
out = "out"
libs = ["lib"]

rpc_url = "https://rpc.apothem.network"
chain_id = 51

# Optionally, you can set the private key here, but it's safer in .env.local
# private_key = "${PRIVATE_KEY}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
